emit:
  - "@typespec/openapi3"
  - "@typespec/json-schema"
  - "@azure-tools/typespec-java"
options:
  "@typespec/json-schema":
    file-type: "json"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/java"
    flavor: generic
    dev-options:
       debug: false